import { LegalLayout, C, font } from '@/lib/components';

export const metadata = { title: 'Terms & Conditions — AnointedLyrics' };

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: 20, fontWeight: 500, color: '#1C1B18', marginBottom: 12 }}>{title}</h2>
      <div style={{ color: 'rgba(28,27,24,.78)', lineHeight: 1.8 }}>{children}</div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <LegalLayout title="Terms & Conditions">
      <Section title="1. Acceptance of Terms">
        By accessing or using AnointedLyrics ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the Service. We reserve the right to update these terms at any time, and continued use constitutes acceptance of any changes.
      </Section>

      <Section title="2. Description of Service">
        AnointedLyrics is an AI-powered lyric generation platform that creates song lyrics and Suno AI style prompts based on user input. The Service is intended for songwriters, musicians, and creative professionals.
      </Section>

      <Section title="3. User Accounts">
        You must create an account to use the Service. You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account. You must provide accurate and complete information when registering. Accounts are for individual use only and may not be shared.
      </Section>

      <Section title="4. Credits and Payments">
        The Service operates on a credit-based system. Credits are purchased in advance and consumed when lyrics are generated. Credits are non-transferable between accounts. Purchased credits do not expire but are subject to our Refund Policy. We reserve the right to adjust credit pricing at any time with reasonable notice.
      </Section>

      <Section title="5. Intellectual Property">
        <p><strong>Your content:</strong> Lyrics generated using your inputs are yours. You retain full ownership of all lyrics generated through the Service and may use them for any commercial or non-commercial purpose, including publishing, recording, and distribution.</p>
        <br />
        <p><strong>Our platform:</strong> The AnointedLyrics name, logo, interface, and underlying technology remain the exclusive property of AnointedLyrics. You may not copy, reproduce, or reverse-engineer any part of the platform.</p>
      </Section>

      <Section title="6. Acceptable Use">
        You agree not to use the Service to generate content that is unlawful, defamatory, harassing, or infringes the rights of third parties. You may not use the Service to generate content that promotes violence, hate speech, or illegal activity. We reserve the right to suspend accounts that violate these terms without refund.
      </Section>

      <Section title="7. AI-Generated Content">
        Lyrics are generated by artificial intelligence. While we strive for quality and originality, we do not guarantee that generated lyrics are unique or free from similarity to existing works. You are responsible for ensuring your use of generated lyrics complies with applicable copyright laws.
      </Section>

      <Section title="8. Availability">
        We aim to maintain high availability but do not guarantee uninterrupted access to the Service. We are not liable for losses resulting from downtime, technical issues, or service interruptions. We reserve the right to modify or discontinue features with reasonable notice.
      </Section>

      <Section title="9. Limitation of Liability">
        To the maximum extent permitted by law, AnointedLyrics shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability to you shall not exceed the amount you paid for credits in the 30 days preceding the claim.
      </Section>

      <Section title="10. Governing Law">
        These Terms shall be governed by and construed in accordance with the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
      </Section>

      <Section title="11. Contact">
        For any questions regarding these Terms, please contact us at{' '}
        <a href="mailto:legal@anointedlyrics.com" style={{ color: '#C6A24B' }}>legal@anointedlyrics.com</a>.
      </Section>
    </LegalLayout>
  );
}
